image: python:3.7


before_script:
  - python -V  # Print out python version for debugging
  - python3 -m venv env
  - source env/bin/activate

run:
  script:
    - pip install -r requirements.txt
    - flake8 .
    - cd src
    - coverage run --rcfile=.coveragerc --source=. manage.py test --settings=app.settings.dev
    - coverage report --fail-under=90

