version: '3'

services:

  backend:
    build: ./
    # image: ulrichkh/testify
    container_name: backend
    restart: always
    command: ./commands/${RUN_MODE}.sh

    ports:
      - 8010:${PORT}
    volumes:
      - ./src:/srv/project/
      - ./commands:/srv/project/commands
      - static_content:/var/www/testify
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.${RUN_MODE}
    env_file:
      - .env

  postgresql:
    image: "postgres:12"
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    env_file: 
      - .env
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/testify
    ports:
     - 80:80
     - 444:443
    depends_on:
      - backend
      
  redis:
    image: redis
    env_file: .env
  #    container_name: redis
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis
    ports:
    - "8081:8081"

  celery:
    env_file: .env
    build: .
    command: ./commands/start_celery.sh
    restart: always
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.${RUN_MODE}
    volumes:
      - ./src:/srv/project/
      - ./commands:/srv/project/commands

  celerybeat:
    env_file: .env
    build: .
    container_name: celerybeat
    command: ./commands/start_celerybeat.sh
    restart: always
    depends_on:
      - celery
    volumes:
      - ./src:/srv/project/
      - ./commands:/srv/project/commands


volumes:
  pgdata: {}
  static_content: {}